### PR TITLE
Add paths to published SMART data on Pangaea

### PR DESCRIPTION
**Pull request by jroettenbacher**
Hi all,
we published the SMART data on Pangaea (DOI: https://doi.org/10.1594/PANGAEA.956151 (in progress)). I'm not sure how to handle this situation correctly but I suggest to add a new entry to the cataloge with the version number in the yaml file name.
This new yaml file would then include all the new files.
I didn't find a way to nicely include Pangaea data in a intake cataloge so I just used the download links. It seems to work just fine that way.

I'm open to suggestions if you think there is a better solution for the published data.

Best
Johannes

### CODE REVIEW

**Comment by mariomech** [comment]
Hej,
is it necessary to have different versions available in intake catalog? Is so, I would rather work with parameters like described in the [intake documentation pp.33](https://intake.readthedocs.io/_/downloads/en/stable/pdf/) and stick with one file per instrument.

**Comment by jroettenbacher** [comment]
It's more of a backward compatibility thing. I don't want to break someone's code because I removed the SMART quicklook data.
I could also just exchange the filepaths in the original smart.yaml file to point to the calibrated data though.

Concerning the parameter approach. I think this might be quite difficult because the urls are so different and not all parameters needed for the AC3 cloud are needed for the Pangaea dataset. I obviously could link to the pubslihed data on the AC3 cloud (since I also uploaded it there) but I rather have the catalogue point to the published data source.

**Comment by mariomech** [comment]
I would say, in the public available intake catalog we have the data referenced that is meant to be for the public. It just make that one default.For myself in Cologne,i have a second intake structure that hosts our primary data and products based on that.Am 09.03.2023 11:42 schrieb Johannes Röttenbacher ***@***.***>:
It's more of a backward compatibility thing. I don't want to break someone's code because I removed the SMART quicklook data.
I could also just exchange the filepaths in the original smart.yaml file to point to the calibrated data though.
Concerning the parameter approach. I think this might be quite difficult because the urls are so different and not all parameters needed for the AC3 cloud are needed for the Pangaea dataset. I obviously could link to the pubslihed data on the AC3 cloud (since I also uploaded it there) but I rather have the catalogue point to the published data source.

**Comment by jroettenbacher** [comment]
Alright, I replaced the SMART quicklook data with the actual pubished data in `smart.yaml` and added the parameter `base_path` to avoid retyping the path everytime. I also included the DOI as metadata as well as the version.
What do you think?
Any more changes which would help a potential user?

**Pull request merged**
